"""Added notes field to ascents table

Revision ID: 3e57a0264bb8
Revises: 8947d5f12e6b
Create Date: 2026-03-04 17:15:45.937188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e57a0264bb8'
down_revision: Union[str, Sequence[str], None] = '8947d5f12e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ascents', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ascents', 'notes')
    # ### end Alembic commands ###
