"""Added UserRouteRelations

Revision ID: 4621dfaffd02
Revises: a1b2c3d4e5f6
Create Date: 2026-03-14 13:33:49.072024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4621dfaffd02'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userroutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('todo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'route_id', name='uq_user_route')
    )
    op.create_index(op.f('ix_userroutes_id'), 'userroutes', ['id'], unique=False)
    op.create_index(op.f('ix_userroutes_route_id'), 'userroutes', ['route_id'], unique=False)
    op.create_index(op.f('ix_userroutes_user_id'), 'userroutes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userroutes_user_id'), table_name='userroutes')
    op.drop_index(op.f('ix_userroutes_route_id'), table_name='userroutes')
    op.drop_index(op.f('ix_userroutes_id'), table_name='userroutes')
    op.drop_table('userroutes')
    # ### end Alembic commands ###
