"""add quality and suggested_grade to ascents

Revision ID: 65291d52a109
Revises: d6b33cf32921
Create Date: 2026-03-04 16:00:22.911695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65291d52a109'
down_revision: Union[str, Sequence[str], None] = 'd6b33cf32921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ascents', sa.Column('quality', sa.Integer(), nullable=True))
    op.add_column('ascents', sa.Column('suggested_grade', sa.Enum('Unknown', 'V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V15', 'V16', 'V17', name='gradeenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ascents', 'suggested_grade')
    op.drop_column('ascents', 'quality')
    # ### end Alembic commands ###
