"""Added desc to Routes and n_attempts to Ascents.

Revision ID: 79fd75746050
Revises: 65291d52a109
Create Date: 2026-03-04 16:04:44.329724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fd75746050'
down_revision: Union[str, Sequence[str], None] = '65291d52a109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ascents', sa.Column('n_attempts', sa.Integer(), nullable=True))
    op.add_column('routes', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'description')
    op.drop_column('ascents', 'n_attempts')
    # ### end Alembic commands ###
