"""add ascent_count to routes

Revision ID: 8947d5f12e6b
Revises: 79fd75746050
Create Date: 2026-03-04 16:23:01.609547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8947d5f12e6b'
down_revision: Union[str, Sequence[str], None] = '79fd75746050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('ascent_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'ascent_count')
    # ### end Alembic commands ###
