"""Adding user annonimization and cascade deletion to ascents and routerelations

Revision ID: f046d8789969
Revises: 4621dfaffd02
Create Date: 2026-03-21 11:37:03.152327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f046d8789969'
down_revision: Union[str, Sequence[str], None] = '4621dfaffd02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ascents_user_id_fkey'), 'ascents', type_='foreignkey')
    op.create_foreign_key(None, 'ascents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('routes_created_by_fkey'), 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'users', ['created_by'], ['username'], ondelete='SET NULL')
    op.drop_constraint(op.f('userroutes_user_id_fkey'), 'userroutes', type_='foreignkey')
    op.create_foreign_key(None, 'userroutes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('walls', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('walls_created_by_fkey'), 'walls', type_='foreignkey')
    op.create_foreign_key(None, 'walls', 'users', ['created_by'], ['username'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'walls', type_='foreignkey')
    op.create_foreign_key(op.f('walls_created_by_fkey'), 'walls', 'users', ['created_by'], ['username'])
    op.alter_column('walls', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'userroutes', type_='foreignkey')
    op.create_foreign_key(op.f('userroutes_user_id_fkey'), 'userroutes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key(op.f('routes_created_by_fkey'), 'routes', 'users', ['created_by'], ['username'])
    op.drop_constraint(None, 'ascents', type_='foreignkey')
    op.create_foreign_key(op.f('ascents_user_id_fkey'), 'ascents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
